In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
import processdata as proda
import torch

In [2]:
data_red = pd.read_csv("winequality\winequality-red.csv", sep = ";")  
data_white = pd.read_csv("winequality\winequality-white.csv", sep = ";")
data_combine = pd.concat([data_red, data_white], ignore_index= True) 

In [3]:
quality = data_combine['quality'].copy() 
data_combine = data_combine.drop(columns=['quality'])

In [4]:
data_white['volatile acidity'].describe()

count    4898.000000
mean        0.278241
std         0.100795
min         0.080000
25%         0.210000
50%         0.260000
75%         0.320000
max         1.100000
Name: volatile acidity, dtype: float64

In [5]:
data_norm = (data_combine - data_combine.mean())/ np.sqrt(data_combine.var())
data_norm = pd.concat([data_norm, quality], axis=1, ignore_index= True).to_numpy(dtype = np.float64)

In [6]:
data_norm[0][0]

0.14246230020599362

In [7]:
list_quality = {int(i) : [] for i in quality.unique()}
for i in range(len(quality)):
    list_quality[int(quality[i])].append(data_norm[i])


In [8]:
Fold = KFold(n_splits=5, shuffle = True)
hehe = Fold.split(list_quality[5])

In [9]:
train = proda.GetDataTrainTest(list_quality, 5)

In [10]:
hehe = proda.MyData(next(train)[1])

In [11]:
x = torch.randn( size=[2,15], requires_grad=True)
y = torch.randn( size=[3,4])

In [24]:
x.view(5,3,2).view(2, 15)

tensor([[ 0.6004,  0.1076,  0.9054, -0.8356, -0.2909, -1.1929, -0.6950,  0.4362,
          0.8472,  0.2749, -0.2038, -0.5227,  0.3498, -0.8696,  0.6458],
        [-0.8754,  0.3987, -0.1804, -1.0451, -1.9399,  0.5642, -1.7350,  0.5807,
          0.6159, -0.9022, -0.7194, -0.0412,  1.2080,  0.4195,  2.9383]],
       grad_fn=<ViewBackward0>)

In [16]:
y = x.transpose(0,1).view(5,3,2).transpose(1,2)

In [36]:
y

tensor([[[ 0.6004,  0.1076,  0.9054],
         [-0.8754,  0.3987, -0.1804]],

        [[-0.8356, -0.2909, -1.1929],
         [-1.0451, -1.9399,  0.5642]],

        [[-0.6950,  0.4362,  0.8472],
         [-1.7350,  0.5807,  0.6159]],

        [[ 0.2749, -0.2038, -0.5227],
         [-0.9022, -0.7194, -0.0412]],

        [[ 0.3498, -0.8696,  0.6458],
         [ 1.2080,  0.4195,  2.9383]]], grad_fn=<TransposeBackward0>)

In [42]:
y.transpose(0,1).view(2,15)

tensor([[ 0.6004,  0.1076,  0.9054, -0.8356, -0.2909, -1.1929, -0.6950,  0.4362,
          0.8472,  0.2749, -0.2038, -0.5227,  0.3498, -0.8696,  0.6458],
        [-0.8754,  0.3987, -0.1804, -1.0451, -1.9399,  0.5642, -1.7350,  0.5807,
          0.6159, -0.9022, -0.7194, -0.0412,  1.2080,  0.4195,  2.9383]],
       grad_fn=<ViewBackward0>)